### ISSUE TITLE
model.predict throws an assertion

### ISSUE THREAD

**Issue by aferust** [p0nce/neural-d#1]
I see this is something in early development, but I cannot take myself from playing around it with:
```
Tensor output;
Tensor input = Tensor(x[N_TEST..N_DATASET]);
model.predict(input, output);
```

core.exception.AssertError@..\..\source\neural\layer.d(51): Assertion failure

**Comment by p0nce** [comment]
Haha! I feel the pressure now ^^

**Comment by p0nce** [comment]
Keep it mind for now the library hasn't ever trained anything.

**Comment by aferust** [comment]
Don't worry take your time, and just enjoy coding. There is [dopt](https://github.com/henrygouk/dopt) also.

**Comment by p0nce** [comment]
The new `predictBatch` call should help. The example now approximate a simple function.
